name: car_on_sale
description: "An app for the Car on Sale coding challenge."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  custom_adaptive_scaffold: ^2.0.1
  dart_jsonwebtoken: ^3.2.0
  flutter:
    sdk: flutter
  freezed_annotation: ^3.0.0
  go_router: ^15.2.3
  http: ^1.4.0
  intl: ^0.20.2
  json_annotation: ^4.9.0
  logging: ^1.3.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  json_serializable: ^6.9.5
  build_runner: ^2.5.3
  freezed: ^3.0.6

flutter:
  assets:
    - assets/
  uses-material-design: true
